### PR TITLE
Fixes compilation on latest nixpkgs

### PR DESCRIPTION
**Pull request by bkchr**
Closes: https://github.com/tpwrules/nixos-apple-silicon/issues/174

### CODE REVIEW

**Comment by minego** [comment]
I ran into the same issue, just did switched my flake to use this branch, and I can confirm that it does work correctly.

**Comment by damien-rezdy** [comment]
I forgot to report back, but I've detected no issue using unstable `nixpkgs` and @bkchr fork , for a day. 
And for a bit of context:  the macbook running nixos on M1 is my work daily driver.

**Comment by tpwrules** [comment]
Had some work stuff so couldn't get to this immediately, thanks all for filing and testing!

**Comment by tpwrules** [comment]
@bkchr FYI the U-Boot fix was incorrect which ended up removing more flags than intended and breaking cross-compilation. See here: https://github.com/tpwrules/nixos-apple-silicon/commit/2aa408936e856f7ea76563cf438083162fba5476

**Comment by bkchr** [comment]
Yeah I realized it as well yesterday, but didn't had the time to fix it! Ty!

**Pull request merged**
