### PR TITLE
asahi-nvram: add asahi-nvram 0.2.1

### PR DESCRIPTION
**Pull request by lukaslihotzki**
This PR adds the asahi-nvram tool. The other tools ([asahi-bless](https://github.com/WhatAmISupposedToPutHere/asahi-nvram/tree/master/asahi-bless), [asahi-btsync](https://github.com/WhatAmISupposedToPutHere/asahi-nvram/tree/master/asahi-btsync), [asahi-wifisync](https://github.com/WhatAmISupposedToPutHere/asahi-nvram/tree/master/asahi-wifisync)) should be similar.

### CODE REVIEW

**Comment by tpwrules** [comment]
It is certainly not attractive that the primary documentation I can find on these tools is "May or may not result in you having to perform a dfu restore.".

I had a brief look though and it seems that they are available in Fedora but not installed by default. Of note, I don't think `asahi-wifisync` will do much because we do not ship iwd by default.

`asahi-bless` looks pretty useful though, and harder to break things with, I'd be fine with just doing that one.

**Comment by alyssais** [comment]
Wouldn't it make more sense to put this in Nixpkgs?

**Comment by tpwrules** [comment]
I would prefer that, yes.

**Comment by lukaslihotzki** [comment]
Ok, I can try to contribute these packages to nixpkgs. After this, it would make sense to also upstream asahi-fwextract, bankstown-lv2, and speakersafetyd.

**Comment by tpwrules** [comment]
I'm not so sure about asahi-fwexctract since it has to match closely with the other components.

**Comment by flokli** [comment]
@lukaslihotzki did you start sending PRs already? Was looking for these tools today, and couldn't find them here or in nixpkgs.

**Comment by lukaslihotzki** [comment]
I have now opened a PR in nixpkgs. I don't know if this will get merged there, but at least the branch can be used manually.

**Comment by lukaslihotzki** [comment]
Now upstreamed by https://github.com/NixOS/nixpkgs/pull/302205

**Pull request closed without merging**
