### PR TITLE
Remove IFD in kernel build

### LINKED ISSUE #51: Pure nix regex parser for the kernel config
The kernel package currently depends on an IFD (import from derivation) to parse the kernel config file.

The file is simple enough that it should be easily doable using pure nix with filter, map, regex match, etc.

This should be upstreamed to nixpkgs if resolved.

### PR DESCRIPTION
**Pull request by QuentinI**
Resolves #51

### CODE REVIEW

**Comment by tpwrules** [comment]
Thank you very much for figuring this out. Is it still technically doing IFD though if there are kernelPatches?

**Comment by QuentinI** [comment]
> Is it still technically doing IFD though if there are kernelPatches?

It's not importing a Nix expr, so as far as I understand it it's more lile a "Read From Derivation", which shouldn't be problematic

**Comment by tpwrules** [comment]
I think it's still problematic because builds have to run before the evaluation can occur. I think the magnitude is much less than before but there is still IFD happening.

**Comment by anna328p** [comment]
> https://github.com/tpwrules/nixos-apple-silicon/pull/70/files#diff-6db5403c64ac81d76097a9d10fbf02809552a396970b1a594d422515de2f0140R37-R43

It's possible to get rid of the IFD by getting rid of `writeFile` here and concatenating the config with the patches in Nix code. Instead of `readFile (writeFile foo)`, we just read `foo`, which isn't the output of a derivation.

I can PR this if needed.

**Pull request merged**
