### PR TITLE
mesa: Upstream removed lib.platforms.mesaPlatforms

### PR DESCRIPTION
**Pull request by rowanG077**
This fixes the build with current nixos-unstable. 

See https://github.com/NixOS/nixpkgs/pull/338337

### CODE REVIEW

**Comment by ibveecnk** [comment]
Thanks for the fix, I can confirm it works.

As I can see, the platforms are now contained in mesas `(mesa.meta) platforms`

https://github.com/alyssais/nixpkgs/blob/ef3692d0559c3ba8b682f07fd8d19669bbee4893/pkgs/development/libraries/mesa/common.nix#L32-L36

I am unsure but but isn't it possible to inherit those platforms in the `mesa-asahi-edge` platforms instead of having two sources of truth?

**Comment by rowanG077** [comment]
The entire mesa package is vendored. Because of this I chose to not depend on the original at all. If @tpwrules wants to do that I can change it.

**Comment by ibveecnk** [comment]
Thats a good point, let's see what @tpwrules says.

**Comment by tpwrules** [comment]
This works and looks good. I would indeed prefer to duplicate the list rather than just change to inherit from a different place. Thank you!

**Pull request merged**
