### PR TITLE
Update m1n1

### PR DESCRIPTION
**Pull request by uuuvn**

### CODE REVIEW

**Comment by tpwrules** [comment]
Is it possible to simply grab the relevant commit(s) as a patch? The change described there should be small.

**Comment by uuuvn** [comment]
Why patch old version when we can just upgrade?

**Comment by tpwrules** [comment]
There have been several occasions where the Asahi folks are unhappy with people grabbing unreleased packages and sending them to users. I don't want to do it. If you want to upgrade you are welcome to and it's easy.

**Comment by uuuvn** [comment]
It's tagged 1.2.8

**Comment by uuuvn** [comment]
And AFAIK released, but in dev branch

**Comment by uuuvn** [comment]
Then maybe separate branch (like asahi reference distro does) is the way to go?

**Comment by uuuvn** [comment]
So people like me who use things like KVM or just want to have latest bleeding-edge version could use it instead of main?

**Comment by tpwrules** [comment]
If you need to use it yourself you can create an overlay in your configuration to change m1n1's version.

**Comment by uuuvn** [comment]
I already done so. The problem is that likely i'm not the only person who wants to eg use KVM. Why don't you think that a "dev" or "next" branch [like asahi reference distro does](https://github.com/AsahiLinux/PKGBUILDs/tree/dev) will be a great idea?

**Comment by uuuvn** [comment]
@tpwrules by the way, yesterday asahi team released a new stable version of packages https://github.com/AsahiLinux/PKGBUILDs . Will you accept PR with versions from stable PKGBUILDs?

**Comment by tpwrules** [comment]
Already been accepted.

**Pull request closed without merging**
