### PR TITLE
uboot-asahi: bug fixes and config updates

### PR DESCRIPTION
**Pull request by zzywysm**
* fix Mac Studios with 8TB internal SSDs.  patch comes from:

https://github.com/jannau/u-boot-1/commits/apple-rtkit-boot-timeout/

* apply Janne Grunau's patch series that fixes font rendering and adds proper cursor support to the EFI console.  These fixes are sufficient to finally fix the NixOS generation boot picker, so that the text renders correctly with no garbage characters at the bottom. In addition, the 5-second timer is now visible. Patch series taken from:

https://github.com/jannau/u-boot-1/commits/asahi-vidconsole-fixes/

* Janne's patch series for font rendering was written against upstream u-boot 2024.01, not the Asahi u-boot branch.  Thus we cherry-pick commits from upstream so that Janne's patches apply cleanly.
* forcefully disable CMD_NFS to achieve the same security improvement as this Fedora Asahi Remix patch:

https://copr-dist-git.fedorainfracloud.org/cgit/@asahi/u-boot/uboot-tools.git/tree/0001-disable-NFS-support-by-default.patch?h=f39

* decrease the boot delay to speed up overall boot time
* disable the submarine logo on boot because it looks goofy

These fixes have all been boot-tested successfully on my MacBook Air M1.

### CODE REVIEW

**Comment by fx-chun** [comment]
I like the boot logo. :(

**Comment by zzywysm** [comment]
> I like the boot logo. :(

Then clearly you'll want to modify the line in this commit that reads `CONFIG_VIDEO_LOGO=n` to `CONFIG_VIDEO_LOGO=y` on your Mac.

In addition, if you really love submarines, you can change the boot logo in the middle of the screen from the Asahi Linux logo to your own PNG file of a magnificent submarine.  Please refer to the `boot.m1n1CustomLogo` property.

**Comment by zzywysm** [comment]
@tpwrules Will you be reviewing this pull request, or shall I close it?

**Comment by tpwrules** [comment]
The bugfixes don't seem unreasonable, but they don't seem that necessary either.

I don't like how these PRs keep getting mixed with opinionated changes.

Let's wait til upstream releases a new U-Boot.

**Comment by zzywysm** [comment]
> I don't like how these PRs keep getting mixed with opinionated changes.

To be clear, by "opinionated changes", you mean these opinions?

* Improving boot time is good
* Acknowledging the u-boot project once during boot is sufficient, two isn't really necessary

I didn't realize I was such a firethrower!

**Comment by tpwrules** [comment]
This persistent pattern of excessively opinionated changes, a sarcastic and one-sided attitude toward discussing them and their implications, and your style of interaction with me and other contributors, is difficult, stressful, and absolutely unwelcome.

You are free to make as many changes as you want to your own config and contribute your changes to the various upstreams, but I am no longer willing to tolerate your behavior and attitude.

**Pull request closed without merging**
